### ISSUE TITLE
Case insensitive parse

### ISSUE THREAD

**Issue by lokoArt** [knowledgecode/date-and-time#29]
parse function is case sensitive.
So this example won't work
`date.parse('29 jul 1990', 'DD MMM YYYY');`

But this one, will work
`date.parse('29 Jul 1990', 'DD MMM YYYY');`

Shouldn't it be case insensitive? Seems like a simple feature

**Comment by knowledgecode** [comment]
Requests for the behavior of the parser are varied, sometimes conflict with each other, so we can't accept all of them. Since we have implemented a mechanism to extend this library, you can use it to rewrite the behavior of the parser as you wish. However, if it ignores case, even such following inputs are allowed as well, it's OK?
```
JUL
jUL
juL
jUl
```
If it's OK, for example, append such the following code:
```javascript
date.extend({
    parser: {
        MMM: function (str) {
            var result = this.find(this.res.MMM.map(m => m.toLowerCase()), str.toLowerCase());
            result.value++;
            return result;
        }
    }
});
```
