### ISSUE TITLE
Addition in a specific time zone

### ISSUE THREAD

**Issue by alex996** [knowledgecode/date-and-time#87]
Thank you for your library. I have a suggestion. I see that in #72 you added `utc?: boolean | undefined` parameter. This is great, because for example, it makes `addHours(dateObj, hours, true)` idempotent no matter what the system time zone is. But it would be more flexible to pass any IANA time zone:

```diff
-export function addHours(dateObj: Date, hours: number, utc?: boolean): Date;
+export function addHours(dateObj: Date, hours: number, timeZone?: string): Date;
```

Or a new function in the timezone plugin:

```diff
+export function addHoursTZ(dateObj: Date, hours: number, timeZone?: string): Date;
```

Here is the example I was testing:

```js
// In the US, the clocks fall back on Nov 3, 2024 at 2:00 am
const mar10 = date.parseTZ("2024-03-10 00:00", "YYYY-MM-DD HH:mm", "America/Chicago"); // UTC-6
const mar11 = date.addDays(mar10, 1); // UTC-5

console.log(mar10.toISOString());
console.log(mar11.toISOString());
```

```sh
# When you run the code on a system in America/Chicago time zone, it's correct:
2024-03-10T06:00:00.000Z
2024-03-11T05:00:00.000Z

# But when you run it on a system that doesn't observe DST, such as America/Sao_Paulo:
2024-03-10T06:00:00.000Z
2024-03-11T06:00:00.000Z
```

I understand that this might be a big ask. For the time being, it might be useful to add a note in the readme, that `add*` functions adjust for DST based on the local time zone, not the date's time zone (unless the 3rd param is `true`, then DST is effectively ignored). In other words, if the user's TZ has different DST rules from the date's TZ, this will impact the math.

**Comment by sseworld** [comment]
You can use it like this
```ts
function addHours(dateObj: Date, hours: number, timeZone?: string): Date {
  return new Date();
}
```

**Comment by knowledgecode** [comment]
@alex996 I've finally completed it. The functions I added are `addYearsTZ()`, `addMonthsTZ()`, and `addDaysTZ()`. I believe these functions will work as you expected. After careful consideration, I decided not to create functions for adding time, such as `addHoursTZ()`, since there are no cases where the calculation results would differ based on time zones. It has been quite some time since I received your feedback, so you might no longer be very interested in this matter, but if you have time, please feel free to try it out.

**Comment by alex996** [comment]
It works, thank you.
